# Generated by Django 4.0 on 2022-05-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewing', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-modified']},
        ),
    ]
