# Generated by Django 4.0 on 2022-06-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewing', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('dog', 'Dog'), ('people', 'People')], default='unspecified', max_length=20, verbose_name='Category'),
        ),
    ]
