# Generated by Django 4.0 on 2022-01-06 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
