# Generated by Django 4.0 on 2022-01-08 01:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test-tag', editable=False, populate_from='title', verbose_name='Tag Address'),
            preserve_default=False,
        ),
    ]
